#!/usr/bin/env zsh

# watch build <cmd>
#   continuously build
#   if fail less
#   else run <cmd> timed
# watch release <cmd>
#   continuously build debug and release
#   if fail copy to ./bin
#   else run <cmd> timed
# watch test
#   continuously build then run test

if [[ "$watch_in_progress" == "" ]]; then
  watch_in_progress=yes nodemon --exec ${0:A} --ext "rs toml" -- $@ 
else
  clear
  cargo build --color=always >&1 >.build-errors 2>&1 
  if [[ "$?" != "0" ]]; then
    clear
    less .build-errors
  else 
    cat .build-errors
    case "$1" in
      release)
        cargo build --release && 
        cp ./target/release/bklyn_zsh ./bin &&
        echo "Copied to bin"
        shift
        if [[ "$@" != "" ]]; then
          time ./target/release/bklyn_zsh $@ ; echo
        fi
        ;;
      test)
        cargo test
        ;;
      *)
        if [[ "$@" != "" ]]; then
          time ./target/debug/bklyn_zsh $@ ; echo
        fi
        ;;
    esac
  fi
fi
